### ISSUE TITLE
Root?

### ISSUE THREAD

**Issue by LuizzAugusto** [mateusmuller/mp3saver#1]
Porquê root?

**Comment by mateusmuller** [comment]
Oi Luiz,
Acabei optando por root por conta das permissões em montar e desmontar o dispositivo.
Dá pra fazer sem também, mas aí tem que configurar as permissões do dispositivo no fstab para usuários normais poderem montar, o que vai dar mais trabalho.
Mas, com certeza vou pensar nisso para os próximos updates.
Se quiser contribuir, sinta-se a vontade!
